# Prisma Cloud IaC Scan Config file. 
# Please update with the respective environment values and commit to master branch under the .github folder before performing scans
# API URL for your Prisma Cloud instance
prisma_cloud_api_url: 'https://api3.prismacloud.io'
# Example:'https://api.eu.prismacloud.io' or 'https://api4.prismacloud.io'						
									
# --Authentication--
# Before adding your keys, to ensure that your keys are not exposed
publicly, make sure that either your repo is private or local to
your organization.
# Create a new access key on the Prisma Cloud web interface (Settings > Access Keys).Copy the credentials below
access_key: 'f9dafc40-e916-44b2-836c-2a0db6a18a7d'
secret_key: 'Q85qvE66I6SxdzJ9g+FQpzpIPdM='
									
# Define the failure criteria for creating checks. If the criteria matches a check will be created. The template for the checks can be customized in the "/.github/prisma-template-for-scan-results" file.
failure_criteria_for_creating_checks:
  high: 1
  medium: 1
  low: 1
  operator: or 
  
# Define the failure criteria for creating issues. If the criteria matches an issue will be created. The template for issues can be customized in the "/.github/prisma-template-for-scan-results" file.
failure_criteria_for_creating_issues:
  high: 1
  medium: 1
  low: 1
  operator: and
